name: Unit and integration test

on:
  push:
    branches: [main, esben]
  pull_request:
    branches: [main, esben]

jobs:
  esben_test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          cache: "uv"

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Test with pytest
        run: |
          uv run pytest