name: Unit and integration test

on:
  push:
    branches: [main, esben]
  pull_request:
    branches: [main, esben]

jobs:
  esben_test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Test with pytest
        run: uv run pytest -v
